title: Swapandeep Kaur
email: swapandeep.kaur@chitkara.edu.in
description: >- 
  Portfolio and personal site of Swapandeep Kaur, Assistant Professor, Chitkara University.
baseurl: ""
url: "https://yourusername.github.io" # Change 'yourusername' to your GitHub username
theme: minima
